### PR TITLE
Flake8

### PR DESCRIPTION
**Pull request by loicgasser**
Fix for https://github.com/geographika/mappyfile/issues/29

I using the default flake8 command to fix the errors.

In the tests I am ignoring line length, as we can have some long mapfile strings.

I fixed most of the errors using autopep8.

A useful command:
`autopep8 --in-place --aggressive --aggressive --verbose $(find mappyfile/* -type f -name "*.py" -print)`

### CODE REVIEW

**Comment by loicgasser** [comment]
I just added a coverage report.

```
Name                       Stmts   Miss  Cover
----------------------------------------------
mappyfile/__init__.py          3      0   100%
mappyfile/ordereddict.py      31     13    58%
mappyfile/parser.py           68      8    88%
mappyfile/pprint.py          173     15    91%
mappyfile/tokens.py            4      0   100%
mappyfile/transformer.py     162     14    91%
mappyfile/utils.py            42      5    88%
mappyfile/validator.py        20     14    30%
----------------------------------------------
TOTAL                        503     69    86%
```

even though the main issue is that you won't know how grammar your actually covering, that's another story.

**Comment by geographika** [comment]
Many thanks for this. I'll review properly next week when I'm back at work.

**Comment by geographika** [comment]
@loicgasser - that's great to have setup. Are you ok with being added to a "Contributers" section in the docs?

**Comment by loicgasser** [comment]
sure

**Pull request merged**
