### PR TITLE
Non-ascii chars are no longer supported in py2

### PR DESCRIPTION
**Pull request by loicgasser**
Since in the transformer we do:

```python
PY2 = sys.version_info[0] < 3
if PY2:
  str = unicode # NOQA
```

fix is trivial.

### CODE REVIEW

**Comment by loicgasser** [comment]
I just added a test to show you that `POSTION UC` is casted to `POSTION "UC"`

As a side note you may want to enbale CORS here:
http://mappyfile.geographika.net/

**Comment by geographika** [comment]
@loicgasser - thanks for reporting this. 
Does adding the following at the top of transformer.py also fix the issue?

`from __future__ import unicode_literals`

See http://python-future.org/imports.html#should-i-import-unicode-literals
This would make it simpler and avoid forgetting the explicit string conversion again in the future.

**Comment by loicgasser** [comment]
Usually I would try to avoid it. It has some weird side effects.
But if you prefer it I can do it. Last quotes from your reference
```
“There are so many subtle problems that unicode_literals causes. For instance lots of people accidentally introduce unicode into filenames and that seems to work, until they are using it on a system where there are unicode characters in the filesystem path.”

—Armin Ronacher
“+1 from me for avoiding the unicode_literals future, as it can have very strange side effects in Python 2.... This is one of the key reasons I backed Armin’s PEP 414.”

—Nick Coghlan
```

Armin Ronacher
https://github.com/mitsuhiko

Nick Coghlan
https://github.com/ncoghlan

But that may be ok in this case...

**Comment by loicgasser** [comment]
seems like I found a fix for the position in labels
https://github.com/geographika/mappyfile/pull/49/commits/a3127a85b403b110bdf6754db7cc2366c937479c
Intreseting that you are finally using json schemas. I like

**Comment by loicgasser** [comment]
ah but position.json is used in other places...

**Comment by loicgasser** [comment]
@geographika I adapted according to you last `wild` push to master. thanks, you can review again

**Comment by geographika** [comment]
Thanks for this. The above changes got integrated into other changes and are included in the 0.6.2 release.

**Pull request closed without merging**
